### ISSUE TITLE
Binary for raspberry and arduino porting

### ISSUE THREAD

**Issue by sorriso93** [mhvis/samil#1]
Hello
considering samilportal is down I'm evaluating alternatives and yours is very interesting.
I don't understand how to install the CLI on a raspberry.
Do you think it is feasible to port it on arduino platform? would be ideal!

**Comment by mhvis** [comment]
You can try downloading the [latest](https://github.com/mhvis/samil/releases/latest) arm binary and run it on Raspberry Pi. You'll need `samil-linux-arm`. There's also a [Python version](https://github.com/mhvis/solar/) which is more maintained, but it is coupled with PVOutput. I don't know if it's possible to port this for Arduino.

**Comment by sorriso93** [comment]
Hello thanks for the reply. Sorry about my ignorance but how can I use the binary on raspberry pi? It's a .dms file and I searched on google finding nothing useful.

**Comment by mhvis** [comment]
The binary is the `samil-linux-arm` file on the linked page, to use it, download it on the Raspberry Pi and execute it on the command line. To see the usage information, put `-h` after the program name, i.e. if you're in the same folder, you type `./samil-linux-arm -h`.

It is not a `.dms` file.
